name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        env:
          DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
        run: |
          echo "Building application"
          mvn -B clean verify --file pom.xml package -DskipTests -P local

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: product-app
          path: target
